### PR TITLE
Allow usage of css classnames instead of inlined styles

### PR DESCRIPTION
**Pull request by Paulomart**
With this PR you can use stylesheets to change the appearance of the generated HTML.

For example this is especially usefull if you want to add text-shadows based on the color of the span. This is a example stylesheet that supports shadows if desired: https://www.sassmeister.com/gist/b6a0ffc551f49ac50aa232c0679cee28

Also this PR refactored the logic of the function, now further modifications should be easier.

### CODE REVIEW

**Comment by Spirit55555** [comment]
I love the idea of CSS classes, but please add a way to change the prefix, like this:
`convertToHTML($text, $line_break_element = false, $inline_styled = true, $css_prefix = 'minecraft-')`

**Comment by Paulomart** [comment]
Would you also be ok with combining both options in one?

eg:
```
convertToHTML($text, $line_break_element = false, $css_prefix = null)
```

When `$css_prefix` is null use inline else use the css classß

**Comment by Spirit55555** [comment]
> Would you also be ok with combining both options in one?
I think that would be confusing, so I would prefer 2 options for it.

**Comment by Paulomart** [comment]
> I think that would be confusing, so I would prefer 2 options for it.

So it would be possible to the the css prefix but not use it?

**Comment by Spirit55555** [comment]
> > I think that would be confusing, so I would prefer 2 options for it.
> 
> So it would be possible to the the css prefix but not use it?

Well yes, but that would not affect the function.

While you are at it, could you change $inline_styled = true to something like $css_classes = false ?
That would make the connection between the options easier to understand.

**Comment by Paulomart** [comment]
Done. I squashed the commits to reduce noice.

**Comment by Spirit55555** [comment]
Thanks for your work :)
I will update the documentation before the next release.

**Pull request merged**
