### PR TITLE
Convert JSON text to legacy

### PR DESCRIPTION
**Pull request by games647**
Since the 1.8 Minecraft servers reply with json text instead of the legacy one. In order to keep it in the same format as the old one I wrote a small class which converts it's back. Inspired by your MinecraftColors class.

Moreover I made some changes to the namespace in the previous PR in order to comply with the PSR-4 standard, so I updated the ReadMe too.

### CODE REVIEW

**Comment by Spirit55555** [comment]
An example in the readme would be nice, everything else looks fine :)

**Comment by games647** [comment]
Added

**Comment by Spirit55555** [comment]
The "More information about Votifier" seems to be in the wrong place now.

**Comment by games647** [comment]
Sorry I completely missed that.

**Pull request merged**
